# docker-compose.yml
version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    environment:
      - FLASK_CONFIG=app.config.ProductionConfig
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    networks:
      - appnet

  worker:
    build:
      context: .
      dockerfile: docker/worker.Dockerfile
    environment:
      - FLASK_CONFIG=app.config.ProductionConfig
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    networks:
      - appnet

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - appnet

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - appnet

volumes:
  pgdata:

networks:
  appnet:
    driver: bridge